[workspace]
resolver = "3"
members = [
    "crates/intime-core",
    "crates/intime-daemon",
    "crates/intime-platform",
    "crates/intime-storage",
    "crates/intime-ai",
    "crates/intime-migrate",
    "crates/intime-e2e",
    "crates/intime-app/src-tauri"
]

default-members = ["crates/intime-daemon"]
